spring:
  application:
    name: ${APP_NAME:Snap Pad}

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/snappad?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:snappad_api}
    password: ${DB_PASSWORD:Snap@Pad123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:thisisaverylongjwtsecretkeywithmorethan32characters123456}
  expiration: ${JWT_EXPIRATION:1200000}

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: WARN

